name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Save authentication token for github registry
        run: echo //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }} >> ~/.npmrc
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - id: doc-cov
        uses: ./
        with:
          working-directory: ./__tests__/example-crate
      - uses: nick-invision/assert-action@v1
        with:
          expected: "80%"
          actual: ${{ steps.doc-cov.outputs.documented }}
      - uses: nick-invision/assert-action@v1
        with:
          expected: "20%"
          actual: ${{ steps.doc-cov.outputs.examples }}
      - uses: nick-invision/assert-action@v1
        with:
          expected: '{"src/foo.rs":{"total":2,"with_docs":2,"total_examples":2,"with_examples":0},"src/lib.rs":{"total":3,"with_docs":2,"total_examples":3,"with_examples":1}}'
          actual: ${{ steps.doc-cov.outputs.json }}
      - uses: nick-invision/assert-action@v1
        with:
          expected: |
            | File       | Documented | Percentage | Examples | Percentage |
            | ---------- | ---------- | ---------- | -------- | ---------- |
            | src/foo.rs | 2          | 100%       | 0        | 0%         |
            | src/lib.rs | 2          | 66.67%     | 1        | 33.33%     |
            | **Total**  | 4          | 80%        | 1        | 20%        |
          actual: ${{ steps.doc-cov.outputs.table }}
      - name: Edit example-crate
        run: printf "/// A test struct\npub struct Bag;" >> ./__tests__/example-crate/src/lib.rs
      - id: diff-doc-cov
        uses: ./
        with:
          working-directory: ./__tests__/example-crate
      - uses: nick-invision/assert-action@v1
        with:
          expected: "+3.33%"
          actual: ${{ steps.diff-doc-cov.outputs.diff-documented }}
      - uses: nick-invision/assert-action@v1
        with:
          expected: "-3.33%"
          actual: ${{ steps.diff-doc-cov.outputs.diff-examples }}
      - uses: nick-invision/assert-action@v1
        with:
          expected: |
            | File       | Documented | Percentage      | Examples | Percentage      |
            | ---------- | ---------- | --------------- | -------- | --------------- |
            | src/foo.rs | 2          | 100% (+0%)      | 0        | 0% (+0%)        |
            | src/lib.rs | 3          | 75% (+8.33%)    | 1        | 25% (-8.33%)    |
            | **Total**  | 5          | 83.33% (+3.33%) | 1        | 16.67% (-3.33%) |
          actual: ${{ steps.diff-doc-cov.outputs.table }}
